# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ include "python-flask-mysql" . }}
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#     - host: "python-flask-mysql.com"
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: {{ include "python-flask-mysql" . }}
#                 port:
#                   number: 80
