replicaCount: 1

image:
  repository: wordpress
  tag: apache
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: alb
  annotations:
     kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/actions.ssl-redirect: >
      {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:region:account-id:certificate/certificate-id
    alb.ingress.kubernetes.io/subnets: subnet-abc123,subnet-def456
  hosts:
    - host: your-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi

resources:
  limits:
    cpu: 375m
    memory: 384Mi
  requests:
    cpu: 250m
    memory: 256Mi

mariadb:
  host: wordpress-mariadb
  port: 3306
  database: bitnami_wordpress
  user: bn_wordpress
  password: base64-encoded-password
