replicaCount: 1

image:
  repository: wordpress
  tag: 5.7.2-apache
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: your-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi

resources:
  limits:
    cpu: 375m
    memory: 384Mi
  requests:
    cpu: 250m
    memory: 256Mi

mariadb:
  host: wordpress-mariadb
  port: 3306
  database: bitnami_wordpress
  user: bn_wordpress
  password: base64-encoded-password
