# values.yaml

jenkins:
  # Service Account
  serviceAccount:
    create: true
    name: jenkins-admin
  # PVC for Jenkins
  persistence:
    enabled: true
    # storageClass: "<my-storage-class>"
    size: "15Gi"
    claimName: jenkins-pv-claim
  # Deployment Config
  deployment:
    image: jenkins/jenkins:lts

  # Service Config
  service:
    type: ClusterIP
    ports:
      httpPort: 8080
      jnlpPort: 50000
  # Agent's PVC for shared Maven repository
  agentPvc:
    enabled: true
    size: "15Gi"
    claimName: repo-storage
