# # templates/pv.yaml

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jenkins-pv
# spec:
#   capacity:
#     storage: {{ .Values.jenkins.persistence.size }}
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: manual
#   hostPath:
#     path: /path/to/your/storage
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: repo-pv
# spec:
#   capacity:
#     storage: {{ .Values.jenkins.agentPvc.size }}
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: manual
#   hostPath:
#     path: /path/to/your/agent/storage
