# templates/pvc-agent.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.jenkins.agentPvc.claimName }}
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jenkins.agentPvc.size }}
