# templates/pvc-jenkins.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.jenkins.persistence.claimName }}
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jenkins.persistence.size }}
