apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins
  namespace: jenkins
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
# ---
# # apiVersion: rbac.authorization.k8s.io/v1
# # kind: RoleBinding
# # metadata:
# #   name: jenkins
# #   namespace: jenkins
# # subjects:
# # - kind: ServiceAccount
# #   name: jenkins
# #   namespace: jenkins
# # roleRef:
# #   kind: Role
# #   name: jenkins
# #   apiGroup: rbac.authorization.k8s.io
