apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    app: {{ include "wordpress.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "wordpress.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "wordpress.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Values.mariadb.host }}
        - name: WORDPRESS_DB_USER
          value: {{ .Values.mariadb.user }}
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress.fullname" . }}-secret
              key: mariadb-password
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.mariadb.database }}
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "wordpress.fullname" . }}-pvc
